export enum LoadersDict {
  GET_BALANCERS_TABLE = 'GET_BALANCERS_TABLE',
  GET_BALANCING_UNIT = 'GET_BALANCING_UNIT',
  GET_VIRTUAL_SERVICES = 'GET_VIRTUAL_SERVICES',
  GET_HOSTS = 'GET_HOSTS',
  GET_DOMAINS = 'GET_DOMAINS',
  GET_CONFIRMATION_CODE = 'GET_CONFIRMATION_CODE',
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
}
